/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2e3131",
        "on-secondary-container": "#626700",
        "tertiary": "#344828",
        "on-tertiary-fixed": "#0e2005",
        "surface-tint": "#116b57",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#b6cea4",
        "surface": "#f9f9f8",
        "surface-container-highest": "#e1e3e2",
        "surface-container": "#edeeed",
        "on-surface": "#191c1c",
        "on-primary-fixed": "#002019",
        "inverse-primary": "#87d5be",
        "on-primary-container": "#92e1c9",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary-container": "#4b603e",
        "outline": "#6f7975",
        "on-surface-variant": "#3f4945",
        "surface-dim": "#d9dad9",
        "secondary": "#5d6300",
        "background": "#f9f9f8",
        "on-secondary-fixed-variant": "#464a00",
        "on-tertiary-container": "#c1d9ae",
        "secondary-fixed": "#e1ec22",
        "secondary-container": "#deea1e",
        "primary-fixed-dim": "#87d5be",
        "primary-fixed": "#a3f2d9",
        "surface-container-low": "#f3f4f3",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f0f1f0",
        "surface-container-high": "#e7e8e7",
        "secondary-fixed-dim": "#c5d000",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#384c2c",
        "tertiary-fixed": "#d1eabe",
        "surface-bright": "#f9f9f8",
        "primary-container": "#076653",
        "error-container": "#ffdad6",
        "surface-variant": "#e1e3e2",
        "outline-variant": "#bec9c4",
        "surface-container-lowest": "#ffffff",
        "primary": "#004c3d",
        "on-background": "#191c1c",
        "on-secondary-fixed": "#1b1d00",
        "on-primary-fixed-variant": "#005141",
        // Lead status colors
        "hot": "#ef4444",
        "warm": "#f59e0b",
        "cold": "#3b82f6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-md": "16px",
        "container-max-width": "1440px",
        "unit": "4px",
        "margin": "32px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "gutter": "24px",
      },
      fontFamily: {
        "sans": ["Inter", "system-ui", "sans-serif"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
